version: "3"

services:
# use jenkins dockerfile with docker installed
  jenkins:
    #image : using the image we built
    build:
      context: ./
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "jenkins_home:/var/jenkins_home"
      - /var/run/docker.sock:/var/run/docker.sock
    


volumes:
  jenkins_home:
